#ifndef LWS_SHORT_H

#include <libwebsockets.h>

typedef struct libwebsocket_context lws_ctx;
typedef struct libwebsocket lws_wsi;
typedef struct libwebsocket_protocols lws_protocols;
typedef enum libwebsocket_callback_reasons lws_callback_reasons;

#define libwebsockets_callback_on_writable lws_callback_on_writeable
#define libwebsocketss_remaining_packet_payload lws_remaining_packet_payload
#define libwebsockets_is_final_fragment lws_is_final_fragment
#define libwebsockets_service lws_service
#define libwebsockets_get_internal_extensions lws_get_internal_extensions
#define libwebsockets_create_context lws_create_context
#define libwebsockets_context_destroy lws_context_destroy

#define LWS_SHORT_H
#endif
